name: DeployAll-$(Date:yyyyMMdd).$(Rev:r)

trigger:
  batch: true
  branches:
    include:
    - master

  paths:
    exclude:
      - logic
      - .gitignore


variables:
  - name: vmImage
    value: "windows-latest"

stages:
  - stage: Build
    jobs:
      - job: "Build"
        pool:
          vmImage: ${{variables.vmImage}}
        steps:
          - template: "templates/build.yml"

  - stage: DEV
    dependsOn: ["Build"]
    jobs:
      - deployment: DEV
        variables:
          - template: "variables/common.yml"
          - template: "variables/dev.yml"
        pool:
          vmImage: ${{variables.vmImage}}
        environment: DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - template: "templates/deploy.yml"
                  parameters:
                    buildNumber: $(Build.BuildNumber)
